### ISSUE TITLE
Not able to make

### ISSUE THREAD

**Issue by pawanjoe** [vetter/shoc#52]
It gives an error:
"
nvcc fatal   : Unsupported gpu architecture 'compute_12'
make[4]: *** [BusSpeedDownload.o] Error 1
make[4]: Leaving directory `/home/pawan/Desktop/summer_school/Intern/shoc-master/src/cuda/level0/epmpi'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/pawan/Desktop/summer_school/Intern/shoc-master/src/cuda/level0'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/pawan/Desktop/summer_school/Intern/shoc-master/src/cuda'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/pawan/Desktop/summer_school/Intern/shoc-master/src'
make: *** [all-recursive] Error 1
"

I have set the right PATH, and configure worked.

**Comment by kspaff** [comment]
Newer versions of CUDA don't support pre-Fermi compute capabilities.

You should remove this flag from CUDA_CPPFLAGS in ./config/common.mk  

Based on the GPU you are testing, you should change the 12 or 20 to the compute capability for your GPU.  You can look that up here:

https://developer.nvidia.com/cuda-gpus

Example with Titan X (remove all -gencode except):

-gencode=arch=compute_52,code=sm_52

**Comment by pawanjoe** [comment]
Thanks! That worked.
